@istest public class Teststudentmastercontroller {
    
     testmethod static  void test1() {
        //Create new expense and insert it into the database        
        //System.runAs(Userinfo.getUserId()
                           Test.startTest();//this will give you a new set of governor limits
                           studentmastercustomcontroller cs = new  studentmastercustomcontroller();
         
                             cs.age=1;
      						   cs.Name = 'teststud1';
                               cs.save1();
                               cs.age=19;
      						   cs.Name = 'teststud1';
                               cs.save1();
         					   Test.stopTest();
         //});
         }

}