@istest
public class TestcustomController {
      
	 testmethod static  void test() {
        //Create new expense and insert it into the database        
        //System.runAs(Userinfo.getUserId()
                           Test.startTest();//this will give you a new set of governor limits
                           customcontrolleraccountsave cs = new  customcontrolleraccountsave();
                               cs.accountnamevariable ='Testaccountcreated';
                               cs.savemyrecord();
         					   Test.stopTest();
                      //Add multiple blocks to test multiple classes in the same test class
                      //  Test.startTest();
                        //   customcontrolleraccountsave cs = new  customcontrolleraccountsave();
                          //     cs.accountnamevariable ='Testaccountcreated';
                             //  cs.savemyrecord();
         				//	   Test.stopTest();
    //});
                           
 
        
        
        
    }
}